uploads = []
outputs = []

[[generated]]
id = "5UEcqc-nxJnEaRUfBO-dN"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "tayyibati app icon"

[[generated]]
id = "AZ4GFHYUjTC2Jb9z8ciWM"
uri = "file://artifacts/mobile/assets/images/splash.png"
type = "image"
title = "tayyibati splash screen"
